### ISSUE TITLE
hackmd 的 slide，字的置左置右怎麼設定呢？

### ISSUE THREAD

**Issue by jawayang** [softnshare/es6#5]
marsen [2:46 PM] 
hi 
請教一下 hackmd 的slide ，
字的置左置右怎麼設定呢？

jacky [2:53 PM] 
直接 hack CSS ，在文件上面加上這段
原本CSS是設定在 .reveal .slides 下面 所以直接附蓋就好 

``` html
<style>
.reveal .slides {
    text-align: left;
}
</style>
```

jacky [3:02 PM] 
如果不要讓標題全部轉大寫要加這段

``` css
h1, h2, h3, h4, h5, h6 {
    text-transform: none !important;
}
```

jacky [3:06 PM] 
簡單說 md 會轉成 HTML 所以你要改什麼都可以
